# Generated by Django 3.2.4 on 2022-05-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_flan_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flan',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
